Quotes/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Quotes.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ViewResult Index()
        {
            return View();
        }
    }
}

Quotes/Controllers/QuotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Quotes;

// Класс для связки
namespace Quotes.Controllers
{
    public class QuotesController : Controller
    {
        private QuotesDBModelContainer db = new QuotesDBModelContainer();

        // GET: Quotes
        public ActionResult Index()
        {
            var quotesSet = db.QuotesSet.Include(q => q.Category);
            return View(quotesSet.ToList());
        }

        // GET: Quotes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quotes quotes = db.QuotesSet.Find(id);
            if (quotes == null)
            {
                return HttpNotFound();
            }
            return View(quotes);
        }

        // GET: Quotes/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.CategoriesSet, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Quotes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "QuoteId,QuoteText,DateAdded,NameOfAuthor,CategoryId")] Quotes quotes)
        {
            if (ModelState.IsValid)
            {
                db.QuotesSet.Add(quotes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.CategoriesSet, "CategoryId", "CategoryName", quotes.CategoryId);
            return View(quotes);
        }

        // GET: Quotes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quotes quotes = db.QuotesSet.Find(id);
            if (quotes == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.CategoriesSet, "CategoryId", "CategoryName", quotes.CategoryId);
            return View(quotes);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "QuoteId,QuoteText,DateAdded,NameOfAuthor,CategoryId")] Quotes quotes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(quotes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.CategoriesSet, "CategoryId", "CategoryName", quotes.CategoryId);
            return View(quotes);
        }

        // GET: Quotes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quotes quotes = db.QuotesSet.Find(id);
            if (quotes == null)
            {
                return HttpNotFound();
            }
            return View(quotes);
        }

        // POST: Quotes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Quotes quotes = db.QuotesSet.Find(id);
            db.QuotesSet.Remove(quotes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Quotes/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>@Html.ActionLink("Цитаты CRUD", "Index", "Quotes")</h2>

Quotes/Views/Quotes/Create.cshtml
@model Quotes

@{
    ViewBag.Title = "Создание цитаты";
}

<h2>Добавить цитату</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Текст цитаты:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuoteText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuoteText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Дата добавления:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateAdded, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateAdded, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Автор цитаты:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameOfAuthor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameOfAuthor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Категория цитаты:</label>
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Quotes/Views/Quotes/Delete.cshtml
@model Quotes

@{
    ViewBag.Title = "Удаление цитаты";
}

<h2>Удаление цитаты</h2>

<h3>Прежде чем сделать это - ПОДУМАЙ!</h3>
<div>
 <hr />
    <dl class="dl-horizontal">
        <dt>
            Цитата:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuoteText)
        </dd>

        <dt>
            Дата добавления:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAdded)
        </dd>

        <dt>
            Автор цитаты:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameOfAuthor)
        </dd>

        <dt>
            Категория:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Вернуться", "Index", new { @type = "button" }, new { @class = "btn btn-warning" })
            <input type="submit" value="Delete" class="btn btn-danger"/> 
        </div>
    }
</div>

Quotes/Views/Quotes/Details.cshtml
@model Quotes

@{
    ViewBag.Title = "Информация о цитате";
}

<h2>Информация о цитате</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Цитата
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuoteText)
        </dd>

        <dt>
           Дата добавления
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAdded)
        </dd>

        <dt>
            Автор цитаты
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameOfAuthor)
        </dd>

        <dt>
            Категория
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.QuoteId }) |
    @Html.ActionLink("Вернуться к списку", "Index")
</p>

Quotes/Views/Quotes/Edit.cshtml
@model Quotes

@{
    ViewBag.Title = "Редактировать цитату";
}

<h2>Редактировать цитату</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.QuoteId)

        <div class="form-group">
            <label class = "control-label col-md-2">Цитата:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuoteText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuoteText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class = "control-label col-md-2">Дата добавления:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateAdded, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateAdded, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class = "control-label col-md-2">Автор Цитаты:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameOfAuthor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameOfAuthor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Категория:</label>
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Quotes/Views/Quotes/Index.cshtml
@model IEnumerable<Quotes>

@{
    ViewBag.Title = "Index";
}

<div class="container">
    <h2>Цитаты</h2>
    <p>
        @Html.ActionLink("Добавить цитату", "Create", new { @type="button" }, new { @class = "btn btn-warning" })
    </p>

  @foreach (var item in Model) {
        <blockquote>
            @Html.DisplayFor(modelItem => item.QuoteText)
            <footer>@Html.DisplayFor(modelItem => item.NameOfAuthor)</footer>
            <footer>@Html.DisplayFor(modelItem => item.Category.CategoryName)</footer>
            <p class="small">@Html.DisplayFor(modelItem => item.DateAdded)</p>
            <div class="btn-group">
                @Html.ActionLink("Edit", "Edit", new { id = item.QuoteId }, new { @class = "btn btn-primary" })
                @Html.ActionLink("Details", "Details", new { id = item.QuoteId }, new { @class = "btn btn-info" })
                @Html.ActionLink("Delete", "Delete", new { id = item.QuoteId }, new { @class = "btn btn-danger" })
            </div>
        </blockquote>
        
    }
    
    <p>
            @Html.ActionLink("Добавить цитату", "Create", new { @type="button" }, new { @class = "btn btn-warning" })
    </p>
   
</div>

Quotes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Цитаты CRUD</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Главная", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Цитаты великих, и не очень ))))</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>